import sys,json,hashlib,subprocess,struct,importlib.util,shutil
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path.cwd();OUT=ROOT/'docs/evidence/SLICE_CONSOLE_R01_DLL_LOAD_CALLSITE_2026-10-04'
helper=ROOT.parent/'analyze_dll_load.py'
if not helper.exists():helper=OUT/'ANALYSIS_HELPER.py'
sp=importlib.util.spec_from_file_location('analysis',helper);analysis=importlib.util.module_from_spec(sp);sp.loader.exec_module(analysis)
read=lambda n:json.loads((OUT/n).read_text())
sha=lambda b:hashlib.sha256(b).hexdigest()
ACCEPTED='5e8c35999cde995c2dbb4a83e520889f4653f135'
git=lambda p:subprocess.check_output([analysis.pe.GIT,'show',ACCEPTED+':'+p])
priorbase='docs/evidence/SLICE_CONSOLE_R01_LOADER_CONTEXT_2026-10-04/'
data=analysis.pe.stable(analysis.TARGET);image=analysis.pe.Image(data);observed=read('STATIC_XREF_OBSERVATION.json')
instructions={row['RVA']:row for block in observed['relevant_function_snippets'] for row in block['instructions']}
prefix={row['RVA']:row for row in observed['path_construction_prefix']}
prior_path=priorbase+'LOADER_CONTEXT_RESULT.json';prior=git(prior_path)
authority={'accepted_commit':ACCEPTED,'accepted_loader_context':{'path':prior_path,'sha256':sha(prior)},'accepted_scope':{'path':priorbase+'ACCEPTED_AUTHORITY.json','sha256':sha(git(priorbase+'ACCEPTED_AUTHORITY.json'))},'initial_static_import_binding':'Preserved UNRESOLVED independently of later DLL-loading call-site','accepted_result_preserved':True}
analysis.put('ACCEPTED_AUTHORITY.json',authority)
runtime_blockers=['GetModuleFileNameW actual output/failure/truncation and CRT path helper results are not observed','Preceding helper/earlier DLL initialization and parent/child dynamic search state not closed','Physical selected module/exports/dependency identities not observed; no process launched','exe startup-time static imports retain independent parent/startup-loader blocker']
site={'CALL_SITE_RVA':'0x5660','CALL_FILE_OFFSET':'0x4a60','CALL_BYTES':'ff15ca290000','CALL_TARGET':{'api':'LoadLibraryExW','module_import':'KERNEL32.dll','IAT_RVA':'0x8030','INT_RVA':'0xa728','evidence':'decoded FF15 RIP memory call references exact import thunk'},
 'ARGUMENT_SOURCE':{'RCX':'lea rcx,[rbp+0x4d0] at0x5652; local constructed UTF16 buffer','RDX':'xor edx,edx at0x5649 -> NULL hFile','R8':'xor r8d,r8d at0x5646 -> DWORD dwFlags0'},
 'DLL_NAME_SOURCE':{'literal_RVA':'0x8868','literal_file_offset':'0x7068','literal':'BambuStudio.dll','copy_RVAs':['0x563f','0x564b','0x5659','0x565c'],'copy_bytes':32,'includes_utf16_NUL':True},
 'PATH_FORM':'CONSTRUCTED_CURRENT_EXECUTABLE_DIRECTORY_PLUS_LITERAL; runtime concrete path unobserved; absolute app-dir form conditional on successful untruncated module filename/path helper results',
 'PATH_CONSTRUCTION':[{'RVA':'0x54a1','API':'GetModuleFileNameW','arguments':'RCX0(current exe), RDX[rbp+0xb0], R8D0x104; return value not checked in shown flow'}, {'RVA':'0x54cf','API':'_wsplitpath','arguments':'path[rbp+0xb0], drive[rbp+0xa0], dir[rbp+0x6e0], fname[rbp+0xae0], ext[rbp+0x8e0]'}, {'RVA':'0x54f2','API':'_wmakepath','arguments':'dest[rbp+0xb0], drive[rbp+0xa0], dir[rbp+0x6e0], fnameNULL, extNULL'}, {'RVA':'0x5610..0x5627','operation':'copy directory UTF16 including NUL into[rbp+0x4d0]'}, {'RVA':'0x5629..0x563d','operation':'find terminator'}, {'RVA':'0x563f..0x565c','operation':'copy two16byte chunks including BambuStudio.dll terminator at directory terminator'}],
 'FLAGS':{'value':0,'hex':'0x00000000','LOAD_LIBRARY_SEARCH_flags':False,'LOAD_WITH_ALTERED_SEARCH_PATH':False,'confidence':'EXACT_LOCAL_INSTRUCTION_ARGUMENT_PROOF'},
 'CONTROL_FLOW_CONTEXT':{'unwind_fragment':['0x550e','0x570b'],'unwind_root':'0x5120','incoming_skip_optional_preload':'0x5508 je0x55f9; both continuing paths converge to directory copy then0x5660','on_success':'0x5669 jne0x56b1; GetProcAddress uses returned HMODULE at0x56b8','on_failure':'0x566b GetLastError then error logging/exit path','export_request':{'CALL_SITE_RVA':'0x56bb','name_source_RVA':'0x88b8','name':'bambustu_main','indirect_export_call_RVA':'0x56e8','actual_function_target':'UNRESOLVED runtime GetProcAddress result'}},
 'SEARCH_CONTEXT_MUTATION_BEFORE_CALL':{'status':'UNRESOLVED','direct_mutation_imports_observed':False,'direct_mutation_calls_in_shown_path_observed':False,'scope':'No direct imported SetDllDirectory/AddDllDirectory/SetDefaultDllDirectories/SetCurrentDirectory names in exe; no claim of global absence','unclosed':'Prior calls/helpers, optional other module LoadLibraryExW0x55db, parent/startup/dynamically-resolved behavior can remain relevant; no other DLL call-site deep dive'},
 'CONFIDENCE':{'api_IAT_call':'HIGH_EXACT_BYTES','literal_path_construction_intent':'HIGH_STATIC_ARGUMENT_FLOW_CONDITIONAL_RUNTIME_INPUT','flags':'HIGH_EXACT_BYTES','actual_path_search_state_binding':'UNRESOLVED'},'CALLSITE_STATUS':'INCOMPLETE','BAMBUSTUDIO_DLL_STATIC_LOAD_INTENT':'RESOLVED','BLOCKERS':runtime_blockers,'EVIDENCE':['STATIC_XREF_OBSERVATION.json','ACCEPTED_AUTHORITY.json'],'LOADED_MODULE_VERIFIED':False}
result={'schema_version':'0.1','status':'HOLD','CALLSITE_STATUS':'INCOMPLETE','BAMBUSTUDIO_DLL_STATIC_LOAD_INTENT':'RESOLVED','intent_resolution_boundary':'Resolves this observed instruction-level DLL load request expression/API/flags, not execution, helper return values, complete search mutation or physical binding','PHYSICAL_MODULE_BINDING':'UNRESOLVED','STATIC_BINDING_RESOLVED':False,'LOADED_MODULE_VERIFIED':False,'relevant_sites':[site],'excluded_same_function_loader_site':{'RVA':'0x55db','reason':'Separate buffer[rbp+0x2c0] with distinct literal-source addresses; only enumerated, no BambuStudio.dll-connected deep analysis'},'remaining_blockers':runtime_blockers,'actions':dict.fromkeys(['Bambu_process_launch','suspended_launch','debugger_attach','ProcMon','loader_trace','module_enumeration','real_slice','descriptor_integration','cache','REUSE','geometry_MINIL_change','printer_send','print','Print_GO_change'],0)}
analysis.put('CALLSITE_RESULT.json',result)
policy='tools/slice-console/policies/ENGINE_RESOURCE_CLOSURE_POLICY_V0_1.json';plan='tools/slice-console/policies/WINDOWS_BAMBU_02080261_LOCK_PLAN.json'
delta={'schema_version':'0.1','policy_id':'windows-bambu-02080261-dll-load-intent-observation-delta-v0.1','accepted_policy':{'path':policy,'sha256':sha(git(policy)),'preserved':True},'accepted_plan':{'path':plan,'sha256':sha(git(plan)),'preserved':True},'accepted_PR46_result':authority['accepted_loader_context'],'new_fact':'RVA0x5660 LoadLibraryExW receives constructed current-exe-directory+BambuStudio.dll buffer with NULL hFile and flags0; flags0 has no explicit LOAD_LIBRARY_SEARCH or altered-path flags','BAMBUSTUDIO_DLL_STATIC_LOAD_INTENT':'RESOLVED','CALLSITE_STATUS':'INCOMPLETE','PHYSICAL_MODULE_BINDING':'UNRESOLVED','STATIC_BINDING_RESOLVED':False,'LOADED_MODULE_VERIFIED':False,'CLOSURE_STATUS':'INCOMPLETE','verified':False,'remaining_runtime_state':runtime_blockers,'initial_startup_static_import_blocker':'Preserved: parent/startup loader context remains unresolved, not addressed by later DLL call-site','Identity_Lock_delta':None,'next_one_recommendation':'AUTHOR STARTUP LOADER EVIDENCE DECISION: review whether static load intent is sufficient and whether a separate bounded startup-context/process-evidence task merits authorization; no launch/trace or native graph starts automatically'}
analysis.put('CLOSURE_POLICY_DELTA_V0_1.json',delta)
checks=[]
def yes(v):assert v
def check(n,fn):fn();checks.append({'name':n,'status':'PASS'})
check('exact_binary_SHA_stable_read',lambda:yes(sha(data)==observed['sha256']=='7680dac4a953cb4f8a96cc2b4ad4ea0b8bfc62f937d3491256922ff24dbb8268'))
check('IAT_INT_identity_loader_imports',lambda:yes(observed['watch_imports']['LoadLibraryExW'][0]['IAT_RVA']=='0x8030' and observed['watch_imports']['GetProcAddress'][0]['IAT_RVA']=='0x8028' and not observed['watch_imports']['LoadLibraryW'] and not observed['watch_imports']['LoadLibraryA']))
check('all_enumerated_xref_bytes_map_to_binary',lambda:yes(len(observed['loader_IAT_xrefs'])==10 and all(image.get(image.rva(int(r['RVA'],16),len(bytes.fromhex(r['bytes']))),len(bytes.fromhex(r['bytes']))).hex()==r['bytes'] for r in observed['loader_IAT_xrefs'])))
check('Bambu_literal_copy_and_string_xref',lambda:yes(bytes.fromhex(observed['DLL_utf16_copy_bytes']).decode('utf-16-le')=='BambuStudio.dll\0' and instructions['0x563f']['RIP_targets']==['0x8868'] and instructions['0x564b']['RIP_targets']==['0x8878']))
check('exact_direct_call_target_displacement',lambda:yes(image.get(image.rva(0x5660,6),6).hex()==site['CALL_BYTES'] and 0x5660+6+struct.unpack('<i',bytes.fromhex(site['CALL_BYTES'])[2:])[0]==0x8030))
check('path_API_IAT_and_buffer_register_flow',lambda:yes(prefix['0x54a1']['import_target']=='GetModuleFileNameW' and prefix['0x54cf']['import_target']=='_wsplitpath' and prefix['0x54f2']['import_target']=='_wmakepath' and instructions['0x5652']['instruction']=='lea rcx, [rbp + 0x4d0]' and instructions['0x5659']['instruction']=='movups xmmword ptr [rax], xmm0' and instructions['0x565c']['instruction']=='movups xmmword ptr [rax + 0x10], xmm1'))
check('flags0_hFile_NULL_local_no_intervening_call',lambda:yes(instructions['0x5646']['instruction']=='xor r8d, r8d' and instructions['0x5649']['instruction']=='xor edx, edx' and not any(r['instruction'].startswith('call ') for block in observed['relevant_function_snippets'] for r in block['instructions'] if 0x5646<=int(r['RVA'],16)<0x5660)))
check('fail_closed_no_physical_or_initial_binding_promotion',lambda:yes(result['CALLSITE_STATUS']=='INCOMPLETE' and result['PHYSICAL_MODULE_BINDING']=='UNRESOLVED' and not result['STATIC_BINDING_RESOLVED'] and bool(result['remaining_blockers']) and json.loads(prior)['STATIC_BINDING_RESOLVED'] is False))
check('accepted_PR46_policy_plan_and_result_bytes_unchanged',lambda:yes(all(subprocess.check_output([analysis.pe.GIT,'show','HEAD:'+p])==git(p) for p in [policy,plan,prior_path]) and delta['accepted_policy']['sha256']=='0e723c91813e0c126f43852bf8bf25faf358d66e42e032fa10c4792b520e8af3'))
check('loaded_false_and_all_actions_zero',lambda:yes(not result['LOADED_MODULE_VERIFIED'] and not site['LOADED_MODULE_VERIFIED'] and not any(result['actions'].values())))
analysis.put('CHECK_RESULTS.json',{'schema_version':'0.1','checks':checks,'pass':len(checks),'fail':0,'existing110_tests':'NOT RERUN: runtime code unchanged; historical PR44 result separate','analysis_tool':'Python3.12.14 / Capstone5.0.6; static bytes only'})
if helper.resolve()!=(OUT/'ANALYSIS_HELPER.py').resolve():shutil.copyfile(helper,OUT/'ANALYSIS_HELPER.py')
if Path(__file__).resolve()!=(OUT/'VERIFICATION_HELPER.py').resolve():shutil.copyfile(__file__,OUT/'VERIFICATION_HELPER.py')
analysis.put('ARTIFACT_DIGESTS.json',{'schema_version':'0.1','algorithm':'SHA256 exact bytes','files':{p.name:sha(p.read_bytes()) for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='ARTIFACT_DIGESTS.json'},'accepted_policy_sha256':delta['accepted_policy']['sha256'],'accepted_plan_sha256':delta['accepted_plan']['sha256']})
print('10 new evidence checks PASS; load intent RESOLVED / callsite context INCOMPLETE / loaded false')
