import assert from "node:assert/strict";
import { boundedJunctionDisplayRadius, boundedPermanentDisplayRadius, buildAstraResearchSnapshot, deriveConnectivityContext, nearestMotifDistance } from "./snapshot.ts";

const open = buildAstraResearchSnapshot("B_OPEN");
const participating = buildAstraResearchSnapshot("B_PARTICIPATING");

assert.equal(open.members.length, 262);
assert.equal(open.attachments.length, 167);
assert.equal(open.junctions.length, 96);
assert.equal(participating.members.length, 325);
assert.equal(participating.attachments.length, 212);
assert.equal(participating.junctions.length, 96);
assert.equal(participating.members.filter((member) => member.layer === "crossLinks").length, 18);
assert.equal(open.source.sourceJunctionCount.provenance, "RECORDED");
assert.equal(open.junctions[0]?.position.provenance, "DERIVED");
assert.equal(open.junctions[0]?.connectedMembers.provenance, "DERIVED");
assert.equal(open.members.find((member) => member.id === "E016")?.addedStage.provenance, "DERIVED");
assert.equal(participating.members.find((member) => member.id === "E146")?.addedStage.provenance, "DERIVED");
assert.equal(open.members.find((member) => member.id === "B_OPEN-G000")?.addedReason.provenance, "NOT RECORDED");
assert.equal(open.fabricationAdditions[0]?.addedStage.provenance, "DERIVED");
assert.equal(open.removableSupports[0]?.role.provenance, "DERIVED");
assert.equal(open.removableSupports[0]?.addedReason.provenance, "NOT RECORDED");
assert.equal(open.fabricationAdditions.find((member) => member.addedReason.value !== null)?.addedReason.provenance, "RECORDED");
const connectedMember = open.members.find((member) => deriveConnectivityContext(open, member).adjacentMembers.value.length > 0);
assert.ok(connectedMember);
const connectedContext = deriveConnectivityContext(open, connectedMember);
assert.equal(connectedContext.adjacentMembers.provenance, "DERIVED");
for (const adjacentId of connectedContext.adjacentMembers.value) {
  const adjacent = open.members.find((member) => member.id === adjacentId);
  assert.ok(adjacent);
  assert.ok(connectedMember.connectedJunctions.value.some((junctionId) => adjacent.connectedJunctions.value.includes(junctionId)));
}
const recordedAttachment = open.attachments.find((member) => member.parentBranch.provenance === "RECORDED");
assert.ok(recordedAttachment);
const attachmentContext = deriveConnectivityContext(open, recordedAttachment);
assert.equal(attachmentContext.recordedParent.provenance, "RECORDED");
assert.equal(attachmentContext.target.provenance, "RECORDED");
const correspondence = open.attachmentCorrespondence.find((entry) => entry.memberId === recordedAttachment.id);
assert.ok(correspondence);
assert.equal(correspondence.branchStart.provenance, "RECORDED");
assert.equal(correspondence.branchEnd.provenance, "RECORDED");
assert.equal(correspondence.surfaceComponentId.provenance, "RECORDED");
const surfaceComponent = open.surfaceComponents.find((component) => component.id === correspondence.surfaceComponentId.value);
assert.ok(surfaceComponent);
assert.equal(surfaceComponent.motifIds.provenance, "RECORDED");
assert.ok(surfaceComponent.motifIds.value.length > 0);
assert.equal(surfaceComponent.attachmentCount.value, open.attachments.filter((member) => member.target.value === `surface component ${surfaceComponent.id}`).length);
const nearestDistance = nearestMotifDistance(open, surfaceComponent.id, correspondence.branchEnd.value);
assert.equal(nearestDistance.provenance, "DERIVED");
assert.equal(typeof nearestDistance.value, "number");
const crossLink = participating.members.find((member) => member.layer === "crossLinks");
assert.ok(crossLink);
assert.equal(deriveConnectivityContext(participating, crossLink).recordedParent.provenance, "NOT RECORDED");
const closeA = { ...connectedMember, id: "CLOSE_A", points: [{ x: 0, y: 0, z: 0 }, { x: 1, y: 0, z: 0 }], connectedJunctions: { value: ["J001"], provenance: "RECORDED" as const } };
const closeB = { ...connectedMember, id: "CLOSE_B", points: [{ x: 1.01, y: 0, z: 0 }, { x: 2, y: 0, z: 0 }], connectedJunctions: { value: ["J002"], provenance: "RECORDED" as const } };
const closeSnapshot = { ...open, members: [closeA, closeB] };
assert.deepEqual(deriveConnectivityContext(closeSnapshot, closeA).adjacentMembers.value, []);
assert.equal(deriveConnectivityContext(closeSnapshot, closeA).adjacentMembers.provenance, "DERIVED");
assert.ok(boundedJunctionDisplayRadius([1.1]) < 1);
assert.equal(boundedPermanentDisplayRadius(1.1), .385);
assert.equal(connectedMember.radius, 1.1);
console.log("ok - Astra Research Reader snapshot counts and provenance");
