import manifest from "./manifest.json";
import "./style.css";
import { graphMetrics, surfaceSummary } from "./analysis.ts";
import {
  loadViewerArtifact,
  verifyReadOnlyIdentity,
  type ViewerArtifact,
} from "./fkeiAdapter.ts";
import { ViewerRenderer, type ViewerRepresentation } from "./renderer.ts";
import {
  createViewerUi,
  setActiveRepresentation,
  setMetadata,
  setRepresentationEnabled,
  setStatus,
  setSummary,
} from "./ui.ts";

const ui = createViewerUi(document.querySelector<HTMLElement>("#app")!, manifest.version, manifest.updatedAt);
const renderer = new ViewerRenderer(ui.viewport);
let artifact: ViewerArtifact | null = null;
let activeRepresentation: ViewerRepresentation = "Geometry";

function number(value: number, digits = 0): string {
  return value.toLocaleString("en-US", { maximumFractionDigits: digits, minimumFractionDigits: digits });
}

function boundsMm(artifactValue: ViewerArtifact): string {
  const size = artifactValue.surface.mmBounds.size;
  return `${number(size.x, 1)} × ${number(size.y, 1)} × ${number(size.z, 1)} mm`;
}

function updateSummary(): void {
  if (!artifact) return;
  const project = artifact.runtime.project;
  if (activeRepresentation === "Geometry") {
    const metrics = graphMetrics(project.finalGraph);
    setSummary(ui, "Geometry", [
      ["Host / Base", `${project.base.host.length} authored metaballs`],
      ["Authored Motifs", `${project.patterns.length} patches`],
      ["Permanent Graph", `${metrics.nodes} nodes / ${metrics.edges} edges`],
      ["Source", "FKEI semantic geometry"],
    ], "Geometry shows the authoritative ingredients: Host / Base, Authored Motifs, and the current Permanent Artwork Structure.");
    return;
  }
  if (activeRepresentation === "Graph") {
    const metrics = graphMetrics(project.finalGraph);
    setSummary(ui, "Graph", [
      ["Nodes", number(metrics.nodes)],
      ["Edges", number(metrics.edges)],
      ["Junctions", number(metrics.junctions)],
      ["Components", number(metrics.components)],
      ["Cycle rank β1", number(metrics.cycleRank)],
    ], "Permanent Artwork Structure only. Removable Support, historical printSupport, and diagnostics graphs are excluded.");
    return;
  }
  if (activeRepresentation === "Surface") {
    const summary = surfaceSummary(artifact.surface);
    setSummary(ui, "Surface", [
      ["Triangles", number(summary.triangles)],
      ["Bounds", boundsMm(artifact)],
      ["Generation", "Canonical Production BODY"],
      ["Material", "Permanent Artwork BODY only"],
    ], "Surface is the final materialized Permanent Artwork BODY generated by the current Production v0 path.");
    return;
  }
  const voidResult = artifact.voidAnalysis;
  const note = artifact.finalBodyExtendsOutsideHost
    ? "Void is evaluated only inside Host / Base envelope. Final BODY extends outside the analysis domain."
    : "Void is evaluated only inside Host / Base envelope; this is an approximate fixed-grid observation, not a clearance or visibility metric.";
  setSummary(ui, "Void", [
    ["Void domain", "Host / Base"],
    ["Grid", `${voidResult.resolution}³ approximate`],
    ["Components", number(voidResult.componentCount)],
    ["Largest component", `${number(voidResult.largestComponentFraction * 100, 1)}%`],
    ["Host/Base-boundary-connected", number(voidResult.boundaryConnectedComponentCount)],
  ], note);
}

function cameraEqual(
  left: ReturnType<ViewerRenderer["cameraState"]>,
  right: ReturnType<ViewerRenderer["cameraState"]>,
): boolean {
  return [...left.position, ...left.target].every((value, index) => {
    const other = [...right.position, ...right.target][index];
    return Math.abs(value - other) <= 1e-8;
  });
}

function switchRepresentation(view: ViewerRepresentation): void {
  if (!artifact) return;
  const beforeCamera = renderer.cameraState();
  renderer.setRepresentation(view);
  const afterCamera = renderer.cameraState();
  activeRepresentation = view;
  setActiveRepresentation(ui, view);
  updateSummary();
  const identityOk = verifyReadOnlyIdentity(artifact);
  if (!identityOk) {
    setStatus(ui, "Read-only identity changed after representation switch.", "error");
    return;
  }
  if (!cameraEqual(beforeCamera, afterCamera)) {
    setStatus(ui, "Camera changed during representation switch.", "error");
    return;
  }
  setStatus(ui, `${view} active · read-only identity unchanged · camera preserved`, "ok");
}

async function loadFile(file: File): Promise<void> {
  ui.openButton.disabled = true;
  ui.sampleButton.disabled = true;
  setStatus(ui, `${file.name} · validating canonical FKEI and building the current Production BODY…`);
  try {
    const next = await loadViewerArtifact(file);
    artifact = next;
    renderer.setSceneData({
      project: next.runtime.project,
      surface: next.surface,
      hostBounds: next.hostBounds,
      voidAnalysis: next.voidAnalysis,
    });
    setMetadata(ui, next.filename, next.schema, next.sourceSha256);
    setRepresentationEnabled(ui, true);
    activeRepresentation = "Geometry";
    setActiveRepresentation(ui, activeRepresentation);
    updateSummary();
    setStatus(ui, `${next.filename} loaded · canonical identity ${next.canonicalHash.slice(0, 16)}… · READ ONLY`, "ok");
  } catch (error) {
    artifact = null;
    setRepresentationEnabled(ui, false);
    setStatus(ui, `FKEI Open failed: ${error instanceof Error ? error.message : String(error)}`, "error");
  } finally {
    ui.openButton.disabled = false;
    ui.sampleButton.disabled = false;
    ui.openInput.value = "";
  }
}

ui.openButton.addEventListener("click", () => ui.openInput.click());
ui.openInput.addEventListener("change", () => {
  const file = ui.openInput.files?.[0];
  if (file) void loadFile(file);
});
ui.sampleButton.addEventListener("click", async () => {
  try {
    const response = await fetch("./samples/skin-rebuild-first-print.fkei", { cache: "no-store" });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    await loadFile(new File([await response.blob()], "skin-rebuild-first-print.fkei", { type: "application/json" }));
  } catch (error) {
    setStatus(ui, `C0 sample failed: ${error instanceof Error ? error.message : String(error)}`, "error");
  }
});
for (const [view, button] of ui.viewButtons) button.addEventListener("click", () => switchRepresentation(view));
ui.resetButton.addEventListener("click", () => {
  renderer.resetView();
  setStatus(ui, "View reset · representation unchanged", "ok");
});

declare global {
  interface Window {
    __FKEI_ANALYSIS_VIEWER__?: { renderer: ViewerRenderer; getArtifact: () => ViewerArtifact | null };
  }
}
window.__FKEI_ANALYSIS_VIEWER__ = { renderer, getArtifact: () => artifact };
